import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import{fileURLToPath}from'node:url';import assert from'node:assert/strict';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const cas=JSON.parse(read('00-depart-cadrage/donnees/cas-coach.json'));
const rows=read('00-depart-cadrage/donnees/evaluations-session-simulee.csv').trim().split(/\r?\n/).slice(1).map(r=>r.split(','));
assert.equal(rows.length,6);assert.equal(new Set(rows.map(r=>r[0])).size,6);assert.equal(cas.session_fictive.presents,6);
for(const r of rows){for(const i of [1,2,3])assert.ok(Number(r[i])>=1&&Number(r[i])<=5);assert.ok(['oui','non'].includes(r[4]));}
const sums=[1,2,3].map(i=>rows.reduce((s,r)=>s+Number(r[i]),0));assert.deepEqual(sums,[12,22,26]);
const complete=rows.filter(r=>r[4]==='oui').length;assert.equal(complete,5);assert.equal(cas.projet.programme.reduce((s,p)=>s+p.minutes,0),90);
const fiche=read('03-livrables/guide/fiche-planning-v2.md');const body=fiche.split(/\n## /).slice(1).map(s=>s.split('\n').slice(1).join(' ')).join(' ');const words=body.trim().split(/\s+/).length;
assert.equal((fiche.match(/^## /gm)||[]).length,5);assert.ok(words>=150&&words<=220,`Longueur ${words}`);assert.ok(fiche.includes('trois résultats'));assert.ok(fiche.includes('marge'));assert.ok(!fiche.includes('500 DH'));
const rapport=read('03-livrables/rapport/rapport-formation-cap-sur-ma-semaine.md');for(const s of ['2,00','3,67','4,33','83,3','+1,67'])assert.ok(rapport.includes(s));
const required=['README.md','00-depart-cadrage/fiche-depart-candidat.md','00-depart-cadrage/objectif-personnel-challenge.md','00-depart-cadrage/carte-usages-ia-personnelle.md','00-depart-cadrage/phrase-engagement-personnel.md','01-prompts/premier-prompt-utilise.md','02-production-controle/fiche-planning-v1.md','02-production-controle/journal-production-correction.md','03-livrables/guide/fiche-planning-v2.md','03-livrables/guide/guide-cap-sur-ma-semaine.md','03-livrables/landing-page/index.html','03-livrables/rapport/rapport-formation-cap-sur-ma-semaine.md','04-portfolio-preuves/portfolio.md','04-portfolio-preuves/preuves-module-01.md'];
const files=required.map(p=>{const bytes=fs.readFileSync(path.join(root,p));return{file:p,bytes:bytes.length,sha256:crypto.createHash('sha256').update(bytes).digest('hex')}});
const result={date_reelle_utc:new Date().toISOString(),nature:'Contrôle technique réel des fichiers du modèle fictif. Aucun acte humain candidat attesté.',fichiers_lus:files,calculs:{effectif:6,sommes:sums,moyenne_avant:sums[0]/6,moyenne_apres:sums[1]/6,satisfaction:sums[2]/6,ecart_moyen:(sums[1]-sums[0])/6,plans_complets:complete,taux_plans_complets:100*complete/6},mots_fiche:words,validation_pedagogique:'Non attribuée',relecture_candidat:'À réaliser'};
if(process.argv.includes('--write')){fs.writeFileSync(path.join(root,'04-portfolio-preuves/trace-technique.json'),JSON.stringify(result,null,2));fs.writeFileSync(path.join(root,'04-portfolio-preuves/controle-technique.md'),'\ufeff'+`# Contrôle technique réel du pack\n\nExécuté le ${result.date_reelle_utc}.\n${files.length} fichiers ouverts et hachés.\nFiche : ${words} mots hors titres et mention de simulation, cinq rubriques.\nCSV : six lignes, identifiants uniques, sommes avant/après/satisfaction 12/22/26.\nMoyennes : 2,00 / 3,67 / 4,33. Écart : +1,67 point. Plans complets : 5/6, soit 83,3 %.\nProgramme du cas : 90 minutes.\n\nCes résultats décrivent les fichiers préparés et les données fictives. Ils ne constituent ni une relecture personnelle de Nadia ni une validation du module. La lecture pédagogique demeure humaine. Voir trace-technique.json pour les empreintes.\n`);}
console.log(JSON.stringify({status:'OK',files:files.length,words,sums,complete,write:process.argv.includes('--write')}));
