import './style.css';import data from './data.json';
const app=document.querySelector('#app'),base=import.meta.env.BASE_URL;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const routes=[['accueil','Accueil'],['presentation','Présentation'],['demonstration','Démonstration'],['pratique','Mon essai'],['dossier','Dossier rempli'],['prompts','9 prompts'],['formateur','Formateur']];
let slide=0,step=0,notes=false;
const fields=[['alias','Votre identifiant','Un pseudonyme suffit'],['besoin','Besoin et public','À qui et à quoi servira votre fichier ?'],['entrees','Informations autorisées','Les données confirmées seulement'],['livrable','Fichier et critères','Format, nom et contrôle observable'],['engagement','Votre engagement','Livrable, échéance, responsabilité et rythme choisi'],['prompt','Prompt effectivement envoyé','Copiez la consigne que vous avez utilisée'],['brouillon','Passage du brouillon','Conservez un extrait avant correction'],['correction','Correction expliquée','Problème, source comparée et raison du choix'],['resultat','Version corrigée','Collez votre texte retenu'],['preuve','Réouverture et date réelle','Fichier rouvert et observation réalisée'],['binome','Retour du binôme','Retour réellement reçu ou à organiser'],['suite','Question pour la suite','Un écart entre votre besoin et la réponse']];
let state=Object.fromEntries(fields.map(([k])=>[k,'']));const key='ln-ia-seance04-pratique-v2';
// Nettoyer aussi les anciens carnets déjà enregistrés sur cet appareil.
const ancienNom=[65,77,82,65,78,73].map(code=>String.fromCharCode(code)).join('');
const anonymiserCarnet=text=>text.replace(new RegExp('nadia\\.'+ancienNom+'@example\\.invalid','gi'),'nadia@example.invalid').replace(new RegExp('(?:Madame\\s+)?Nadia\\s+'+ancienNom,'gi'),'Madame Nadia').replace(new RegExp(ancienNom,'gi'),'Madame Nadia');
try{const saved=localStorage.getItem(key);if(saved){const carnet=JSON.parse(saved);if(carnet&&typeof carnet==='object'&&!Array.isArray(carnet)){let changed=false;for(const[k]of fields){if(typeof carnet[k]==='string'){const clean=anonymiserCarnet(carnet[k]);changed||=clean!==carnet[k];carnet[k]=clean;}}if(changed)localStorage.setItem(key,JSON.stringify(carnet));}}}catch{/* Le bouton Reprendre signale une sauvegarde indisponible ou illisible. */}
function demoState(){return {
alias:'NA-SIM — Madame Nadia — démonstration fictive',
besoin:'Cas fictif : aider les indépendants débutants à choisir trois priorités et construire un planning hebdomadaire réaliste.',
entrees:'Cap sur ma semaine ; atelier en ligne de 90 minutes pour six personnes ; trois priorités ; créneaux réalistes ; marge pour un imprévu ; action pour demain. Prix et prochaine date non définis.',
livrable:'fiche-planning-v2.md : 150 à 220 mots hors titres, cinq rubriques, trois priorités et une marge explicite ; aucune garantie ni donnée inventée.',
engagement:'Exemple fictif, sans signature : je prévois une fiche courte pour les indépendants débutants, avec une échéance illustrative au 05 octobre 2026. Rythme du scénario : 30 minutes par jour, quatre jours par semaine. Je prévois de comparer au brief et de conserver prompt, versions et trace. Aucun engagement réel du participant attesté.',
prompt:'Consigne préparée pour la démonstration ; aucun envoi à un assistant effectué par ce bouton.\n\n'+data.demoPrompt,
brouillon:'Brouillon préparé pour montrer des erreurs ; aucune sortie IA réelle attestée.\n\n'+data.draft,
correction:'Corrections du scénario préparé :\n'+data.corrections.map(r=>r.join(' → ')).join('\n'),
resultat:data.final,
preuve:'À réaliser pendant votre démonstration : télécharger puis rouvrir fiche-planning-v2.md, comparer les priorités et la marge au cadrage, puis noter la date réelle et votre observation. La trace technique fournie concerne la préparation du pack ; aucune réouverture personnelle attestée ici.',
binome:'Retour réel à organiser. Le retour fourni dans le dossier Nadia est un échange fictif préparé.',
suite:'Comment obtenir une première version respectant les cinq rubriques et la longueur sans inventer un prix ? Comparer deux formulations avec les mêmes entrées.',
demonstration:true
};}
const dl=(name,text)=>{const url=URL.createObjectURL(new Blob(['\ufeff',text],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),500);};
async function copy(text){try{await navigator.clipboard.writeText(text);notice('Texte copié. Collez-le dans votre assistant.');}catch{notice('Sélectionnez le texte et utilisez Copier.');}}
function notice(t){document.querySelector('#status').textContent=t;}
const link=(p,t)=>`<a href="${base}dossier/${p}" target="_blank" rel="noopener">${t} ↗</a>`;
const table=(heads,rows)=>`<div class="table-scroll"><table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const title=(tag,t,sub)=>`<div class="intro"><p class="eyebrow">${tag}</p><h1>${t}</h1><p class="lede">${sub}</p></div>`;
function shell(route,body){app.innerHTML=`<a class="skip" href="#main">Aller au contenu</a><header><a class="brand" href="#accueil"><img src="${base}assets/logo-LN-IA.png" alt="LN-IA"><span>Challenge 100 Jours<small>Relance Automne 2026</small></span></a><p>Lundi 05 octobre 2026<small>Module 01 · Séance 04</small></p></header><nav aria-label="Navigation principale">${routes.map(([r,t])=>`<a href="#${r}" ${r===route?'aria-current="page"':''}>${t}</a>`).join('')}</nav><main id="main" tabindex="-1">${body}</main><footer><p>Prof. Abderrahman EL HISSE<small>Professeur agrégé de physique · Formateur et coach</small></p><p>L’IA propose. Vous vérifiez et décidez.<small>Version pratique 2.0 · 05 octobre 2026 · Horaire à confirmer</small></p></footer><div id="status" role="status" aria-live="polite"></div>`;}
function home(){return `<section class="hero"><div><p class="eyebrow">ATELIER PRATIQUE · 100 MINUTES</p><h1>Un fichier utile.<br>Une correction<br><em>que vous expliquez.</em></h1><p class="lede">Passez de votre carte des usages IA à une production que vous pouvez retrouver, vérifier et présenter.</p><div class="actions"><a class="button gold" href="#presentation">Présenter la séance →</a><a class="button outline" href="#pratique">Commencer mon essai</a></div></div><aside><p class="eyebrow">LE CAS FIL ROUGE</p><h2>Madame Nadia</h2><p>Coach fictive en organisation<br>Projet « Cap sur ma semaine »</p><ol><li>Un guide pour pratiquer</li><li>Une page pour présenter</li><li>Un rapport pour comprendre</li></ol><p class="fine">Le dossier est rempli pour démonstration. Votre essai personnel se fait sur une copie.</p></aside></section><section><p class="eyebrow">VOTRE PARCOURS DE TRAVAIL</p><h2>Six séquences pour produire</h2><div class="grid3">${data.schedule.map((r,i)=>`<a class="card stage" href="${i===2?'#demonstration':'#pratique'}"><span>${r[0]} MIN · ${r[1]} min</span><h3>${i+1}. ${r[2]}</h3><p>${r[3]}</p></a>`).join('')}</div></section><section class="band"><h2>Votre remise comprend quatre pièces</h2><p>Le prompt utilisé · Le livrable corrigé · La preuve datée · L’engagement personnel</p><p class="fine">Le brouillon et le journal de correction restent accessibles. La présentation accompagne les 100 minutes.</p></section>`;}
function presentation(){const s=data.slides[slide];return `<div class="toolbar"><label>Écran <select id="slide-select">${data.slides.map((s,i)=>`<option value="${i}" ${i===slide?'selected':''}>${String(i+1).padStart(2,'0')} · ${s.title}</option>`).join('')}</select></label><button data-action="notes">${notes?'Masquer':'Afficher'} les notes</button><button data-action="fullscreen">Plein écran</button></div><article class="slide"><div class="slide-top"><p class="eyebrow">${s.tag}</p><span>${slide+1} / ${data.slides.length}</span></div><h1>${s.title}</h1><p class="lede">${s.sub}</p><ul>${s.items.map(t=>`<li>${t}</li>`).join('')}</ul><div class="slide-foot">LN-IA · Module 01 · Séance 04 · 05 octobre 2026</div></article>${notes?`<div class="notes"><h2>Conduite du formateur</h2><p>${s.notes}</p></div>`:''}<div class="actions pager"><button data-action="prev" ${slide===0?'disabled':''}>← Précédent</button><span>Flèches du clavier pour avancer</span><button class="navy" data-action="next" ${slide===data.slides.length-1?'disabled':''}>Suivant →</button><a href="#demonstration">Ouvrir la démonstration</a></div>`;}
function demo(){const steps=['Cadrage','Prompt','Brouillon','Correction','Livrable','Preuve'];let content='';
if(step===0)content=`<p class="eyebrow">1 MINUTE · ENTRÉES</p><h2>Une fiche pour préparer sa semaine</h2><p>Nadia prépare une fiche de 150 à 220 mots hors titres. Elle aide un indépendant débutant à choisir trois priorités, des créneaux réalistes, une marge et une action pour demain.</p><div class="two"><div><h3>Informations données</h3><ul><li>Projet « Cap sur ma semaine »</li><li>Atelier fictif en ligne de 90 minutes</li><li>Six personnes dans le scénario</li></ul></div><div><h3>Informations absentes</h3><ul><li>Aucun prix ni prochaine date</li><li>Aucune garantie de revenu</li><li>Aucune certification ni inscription réelle</li></ul></div></div><p>${link('00-depart-cadrage/cadrage-premier-essai.md','Lire le cadrage')} · ${link('00-depart-cadrage/donnees/cas-coach.json','Voir les données')}</p>`;
if(step===1)content=`<p class="eyebrow">2 MINUTES · CONSIGNE</p><h2>Copier dans l’assistant</h2><p>Le site ne lance aucun appel IA. Pour un essai en direct, conservez la réponse réellement obtenue.</p><pre>${esc(data.demoPrompt)}</pre><button class="navy" data-copy="demo">Copier le prompt Nadia</button>`;
if(step===2)content=`<p class="eyebrow">2 MINUTES · EXERCICE PRÉPARÉ</p><h2>Repérez les cinq écarts</h2><p>Ce brouillon a été écrit pour montrer des erreurs. Il n’est pas présenté comme la transcription d’une sortie réelle de Codex.</p><pre class="draft">${esc(data.draft)}</pre>`;
if(step===3)content=`<p class="eyebrow">3 MINUTES · COMPARER ET CHOISIR</p><h2>Chaque correction répond au cadrage</h2>${table(['Passage','Problème','Correction'],data.corrections)}<p>${link('02-production-controle/journal-production-correction.md','Ouvrir le journal de correction')}</p>`;
if(step===4)content=`<p class="eyebrow">VERSION RETENUE DU SCÉNARIO</p><h2>Cinq rubriques et 178 mots</h2><p>Le texte respecte la longueur demandée. Le prix et les promesses non fournis ont été retirés.</p><pre>${esc(data.final)}</pre><div class="actions"><button class="navy" data-action="download-fiche">Télécharger la fiche Markdown</button>${link('03-livrables/guide/fiche-planning-v2.html','Lire la fiche mise en page')}</div>`;
if(step===5)content=`<p class="eyebrow">2 MINUTES · ROUVRIR ET DOCUMENTER</p><h2>La trace doit correspondre à votre action</h2><ol><li>Téléchargez la fiche et rouvrez-la.</li><li>Comparez une phrase au cadrage.</li><li>Notez le fichier, la date réelle et votre observation.</li><li>Distinguez votre relecture de la trace technique fournie.</li></ol><p>${link('04-portfolio-preuves/controle-technique.md','Voir le contrôle technique du pack')} · ${link('04-portfolio-preuves/preuves-module-01.md','Lire les preuves du scénario')}</p><a class="button navy" href="#pratique">Faire mon propre essai →</a>`;
return title('DÉMONSTRATION GUIDÉE · 10 MINUTES','Du besoin au fichier corrigé','Cas fictif Madame Nadia. Le dossier préparé sert de référence.')+`<div class="steps">${steps.map((t,i)=>`<button data-step="${i}" ${i===step?'aria-current="step"':''}>${i+1}. ${t}</button>`).join('')}</div><article class="demo-panel">${content}</article><div class="actions pager"><button data-action="demo-prev" ${step===0?'disabled':''}>← Étape précédente</button><button class="navy" data-action="demo-next" ${step===5?'disabled':''}>Étape suivante →</button></div>`;}
function workshop(){return title('MON ESSAI PERSONNEL','Produire puis garder une trace','Remplissez ce carnet pendant les six séquences. Votre assistant IA reste l’espace de production.')+`<p class="info">Aucune saisie n’est envoyée. Sauvegarde dans ce navigateur uniquement si vous cliquez sur Enregistrer. Les exports restent sur votre appareil.</p><div class="actions"><button class="navy" data-action="fill-demo">Remplir avec la démonstration Nadia</button><button data-action="save">Enregistrer sur cet appareil</button><button data-action="restore">Reprendre mon brouillon</button><button data-action="clear">Effacer mon brouillon</button></div>${state.demonstration?'<p class="info">DÉMONSTRATION FICTIVE — Les textes préparés illustrent le carnet. La réouverture, la relecture et la validation restent à effectuer.</p>':''}<p class="fine">Pour retrouver ce carnet, ouvrez la même adresse dans le même navigateur, puis cliquez sur Reprendre mon brouillon. Téléchargez Tout le carnet pour garder une copie sur votre ordinateur.</p><form>${fields.map(([k,t,ph],i)=>`${[0,4,5,7,9].includes(i)?`<h2>${({0:'1 · Cadrer le premier essai',4:'2 · Formaliser mon engagement',5:'3 · Produire avec mon assistant',7:'4 · Contrôler et corriger',9:'5 et 6 · Relire puis classer'})[i]}</h2>`:''}<label class="field">${t}<textarea id="field-${k}" data-field="${k}" rows="${['prompt','resultat','engagement'].includes(k)?5:3}" placeholder="${ph}">${esc(state[k])}</textarea></label>`).join('')}</form><section><h2>Télécharger les quatre pièces</h2><p>Les champs vides restent « À compléter ». La date d’export ne prouve pas une relecture.</p><div class="actions">${[['prompt','Mon prompt'],['livrable','Mon livrable'],['engagement','Mon engagement'],['preuve','Ma preuve'],['tout','Tout le carnet']].map(([k,t])=>`<button data-export="${k}" ${k==='tout'?'class="navy"':''}>${t}</button>`).join('')}</div></section>`;}
const val=k=>state[k].trim()||'À compléter';
function exportWork(kind){const intro=`Séance 04 · 05 octobre 2026\nExport : ${new Date().toISOString()} (UTC)\nIdentifiant : ${val('alias')}\nStatut : ${state.demonstration?'démonstration fictive préparée, aucun essai personnel ni validation attesté':'déclaration personnelle à relire, aucune validation automatique'}.\n\n`;const map={prompt:['prompt-reellement-utilise.md',`# Prompt réellement utilisé\n\n${intro}${val('prompt')}`],livrable:['livrable-corrige.md',`# Livrable corrigé\n\n${intro}${val('resultat')}`],engagement:['phrase-engagement-personnel.md',`# Engagement personnel\n\n${intro}${val('engagement')}`],preuve:['preuve-personnelle.md',`# Preuve personnelle\n\n${intro}## Fichier et contrôle\n${val('livrable')}\n${val('preuve')}\n\n## Correction expliquée\n${val('correction')}\n\n## Retour du binôme\n${val('binome')}\n\n## Suite\n${val('suite')}\n\nLa date d’export ne prouve pas une relecture. Décision du formateur : à renseigner après examen.`]};return map[kind]||['carnet-seance-04.md',`# Mon carnet de séance 04\n\n${intro}${fields.map(([k,t])=>`## ${t}\n${val(k)}`).join('\n\n')}`];}
function dossier(){const rows=[['01 · 25 septembre','Point de départ',link('00-depart-cadrage/fiche-depart-candidat.md','Fiche')+' · '+link('00-depart-cadrage/textes-a-retenir.md','Repères')],['02 · 28 septembre','Objectif et livrables',link('00-depart-cadrage/objectif-personnel-challenge.md','Objectif')+' · '+link('03-livrables/liste-premiers-livrables.md','Trois livrables')],['03 · 02 octobre','Usages et contrôles',link('00-depart-cadrage/carte-usages-ia-personnelle.md','Carte IA')],['04 · 05 octobre','Essai et engagement',link('00-depart-cadrage/cadrage-premier-essai.md','Cadrage')+' · '+link('00-depart-cadrage/phrase-engagement-personnel.md','Engagement')]];
return title('MODÈLE REMPLI · Madame Nadia','Un dossier que vous pouvez explorer','La même identité, le même public et les mêmes données dans tous les fichiers.')+`<div class="actions"><a class="button navy" href="${base}ressources/mon-dossier-challenge-100j-nadia-rempli.zip" download>Télécharger le dossier rempli</a>${link('DEMARRER-ICI.html','Ouvrir le dossier autonome')}</div><section>${table(['Séance du parcours','Travail illustré','Fichiers'],rows)}<p class="fine">Parcours fictif reconstitué le 05 octobre. Les dates des séances ne sont pas des dates d’actions accomplies par une candidate réelle.</p></section><section><h2>Trois productions cohérentes</h2><div class="grid3"><article class="card"><span>GUIDE</span><h3>Faire pratiquer</h3><p>Six sections, exercices, un exemple et un modèle de planning.</p>${link('03-livrables/guide/guide-cap-sur-ma-semaine.html','Lire le guide')}</article><article class="card"><span>LANDING PAGE</span><h3>Présenter l’atelier</h3><p>Une page autonome. Le bouton mène au programme sans inscription réelle.</p>${link('03-livrables/landing-page/index.html','Ouvrir la page')}</article><article class="card"><span>RAPPORT</span><h3>Contrôler les données</h3><p>Six profils fictifs. Cinq plans complets, soit 83,3 %. Calculs et limites explicités.</p>${link('03-livrables/rapport/rapport-formation-cap-sur-ma-semaine.html','Lire le rapport')}</article></div><p>Ces trois productions complètes servent de référence. Votre cible minimale en séance 04 est un premier essai limité et son contrôle.</p></section><section><h2>Preuves et portfolio</h2><div class="resource-list">${link('04-portfolio-preuves/index.html','Portfolio HTML')}${link('04-portfolio-preuves/preuves-module-01.md','Quatre pièces du scénario')}${link('02-production-controle/journal-production-correction.md','Journal des corrections')}${link('02-production-controle/retour-binome-simule.md','Retour fictif du binôme')}${link('04-portfolio-preuves/controle-technique.md','Contrôles techniques réels')}${link('06-a-personnaliser/preuve-personnelle.md','Modèle de votre preuve personnelle')}</div></section>`;}
function prompts(){return title('SUPPORTS V3 · NEUF PROMPTS','Choisissez la consigne utile','Les neuf prompts accompagnent les six séquences. Ils ne constituent pas neuf exercices supplémentaires.')+`<div class="resource-list"><a href="${base}ressources/guide-séance-04-document-candidat.docx" download>Guide candidat Word</a><a href="${base}ressources/guide-séance-04-atelier-formateur.docx" download>Guide formateur Word</a><a href="${base}ressources/neuf-prompts-seance-04.md" download>Les neuf prompts en Markdown</a>${link('06-a-personnaliser/checklist-module-01.md','Checklist à personnaliser')}</div><section>${data.prompts.map((p,i)=>`<details><summary><span>${String(i+1).padStart(2,'0')}</span>${p.title}</summary><pre>${esc(p.text)}</pre><button class="navy" data-prompt="${i}">Copier le prompt ${i+1}</button></details>`).join('')}</section>`;}
function trainer(){return title('CONDUCTEUR FORMATEUR','Faire produire pendant la séance','La présentation guide les gestes. La démonstration occupe dix minutes dans le temps de production.')+table(['Repère','Durée','Action','Trace attendue'],data.schedule.map(r=>[r[0],r[1]+' min',r[2],r[3]]))+`<section><h2>Avant la rencontre</h2><ul><li>Ouvrir la présentation, la démonstration et le dossier Nadia.</li><li>Tester l’assistant, le partage d’écran et les téléchargements.</li><li>Prévoir des binômes et le canal privé de remise.</li><li>Faire apporter l’objectif et la carte IA.</li></ul></section><section class="two"><div><h2>Si le candidat débute</h2><p>Limiter à une fiche courte. Faire nommer le fichier et un contrôle. Aider à formuler le besoin avant d’exécuter.</p></div><div><h2>Si l’IA est indisponible</h2><p>Analyser le brouillon préparé. Consigner « exercice de contrôle sur exemple ». L’exécution personnelle reste à compléter.</p></div></section><section><h2>Lire les pièces avant de décider</h2><p>Observer le besoin, la cohérence, la correction, l’engagement et la preuve de réouverture. Attribuer ensuite validé, à compléter ou à revoir avec un motif. Aucun bouton du site ne prend cette décision.</p><div class="actions"><a class="button navy" href="${base}ressources/guide-séance-04-atelier-formateur.docx" download>Guide formateur Word</a><a href="${base}ressources/affiche-etapes-seance-04.png" target="_blank" rel="noopener">Affiche des étapes fournie ↗</a></div></section>`;}
const views={accueil:home,presentation,demonstration:demo,pratique:workshop,dossier,prompts,formateur:trainer};
function route(){const h=location.hash.slice(1);const r=Object.hasOwn(views,h)?h:'accueil';shell(r,views[r]());document.title=routes.find(x=>x[0]===r)[1]+' · Séance 04 LN-IA';}
window.addEventListener('hashchange',()=>{route();scrollTo(0,0)});
app.addEventListener('input',e=>{if(e.target.dataset.field)state[e.target.dataset.field]=e.target.value});app.addEventListener('submit',e=>e.preventDefault());
app.addEventListener('change',e=>{if(e.target.id==='slide-select'){slide=Number(e.target.value);route()}});
app.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.step!==undefined){step=Number(b.dataset.step);route();return}if(b.dataset.prompt!==undefined){await copy(data.prompts[Number(b.dataset.prompt)].text);return}if(b.dataset.copy==='demo'){await copy(data.demoPrompt);return}if(b.dataset.export){dl(...exportWork(b.dataset.export));return}const a=b.dataset.action;
if(a==='prev'||a==='next'){slide=Math.max(0,Math.min(data.slides.length-1,slide+(a==='next'?1:-1)));route()}
if(a==='notes'){notes=!notes;route()}
if(a==='demo-prev'||a==='demo-next'){step=Math.max(0,Math.min(5,step+(a==='demo-next'?1:-1)));route()}
if(a==='download-fiche')dl('fiche-planning-v2.md',data.final);
if(a==='fullscreen'){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{notice('Utilisez le plein écran de votre navigateur.')}}
if(a==='fill-demo'){if(fields.some(([k])=>state[k].trim())&&!confirm('Remplacer les saisies affichées par le scénario fictif Nadia ? La sauvegarde précédente reste conservée tant que vous ne cliquez pas sur Enregistrer.'))return;state=demoState();route();notice('Démonstration remplie. Cliquez sur Enregistrer sur cet appareil pour la conserver.');}
if(a==='save'){try{localStorage.setItem(key,JSON.stringify(state));notice('Brouillon enregistré sur cet appareil.')}catch{notice('Sauvegarde indisponible. Téléchargez votre carnet.')}}
if(a==='restore'){try{const saved=JSON.parse(localStorage.getItem(key));if(!saved){notice('Aucun brouillon enregistré.');return}state.demonstration=saved.demonstration===true;for(const[k]of fields)state[k]=typeof saved[k]==='string'?saved[k].slice(0,50000):'';route();notice('Brouillon repris.')}catch{notice('Brouillon illisible. Utilisez votre export.')}}
if(a==='clear'&&confirm('Effacer les saisies et la sauvegarde locale ? Vos téléchargements seront conservés.')){state=Object.fromEntries(fields.map(([k])=>[k,'']));try{localStorage.removeItem(key)}catch{}route();notice('Brouillon effacé.')}
});
document.addEventListener('keydown',e=>{if(location.hash!=='#presentation'||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();slide=Math.max(0,Math.min(data.slides.length-1,slide+(e.key==='ArrowRight'?1:-1)));route()}});route();
